version: '3'
services:
  sothib: 
    container_name: sothib
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3200:3000
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
    networks:
      - data_analytics
networks:
  data_analytics: 
    external: true
